# Generated by Django 6.0.7 on 2026-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phoneotp_account_alter_phoneotp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('verify_phone', 'Verify Phone'), ('reset_password', 'Reset Password')], default='verify_phone', max_length=30),
        ),
    ]
