# Generated by Django 6.0.7 on 2026-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
    ]
